<div class='flex flex-row'>
  <button class='border' style='width: 20px; height: 20px;'></button>
  <button class='border' style='width: 20px; height: 20px;'></button>
  <button class='border' style='width: 20px; height: 20px;'></button>
  <button class='border' style='width: 20px; height: 20px;'></button>
  <button class='border' style='width: 20px; height: 20px;'></button>
  <button class='border' style='width: 20px; height: 20px;'></button>
  <button class='border' style='width: 20px; height: 20px;'></button>
  <button class='border' style='width: 20px; height: 20px;'></button>
  <button class='border' style='width: 20px; height: 20px;'></button>
  <button class='border' style='width: 20px; height: 20px;'></button>
  <button class='border' style='width: 20px; height: 20px;'></button>
  <button class='border' style='width: 20px; height: 20px;'></button>
  <button class='border' style='width: 20px; height: 20px;'></button>
  <button class='border' style='width: 20px; height: 20px;'></button>
  <button class='border' style='width: 20px; height: 20px;'></button>
  <button class='border' style='width: 20px; height: 20px;'></button>
  <button class='border' style='width: 20px; height: 20px;'></button>
  <button class='border' style='width: 20px; height: 20px;'></button>
  <button class='border' style='width: 20px; height: 20px;'></button>
  <button class='border' style='width: 20px; height: 20px;'></button>
  <button class='border' style='width: 20px; height: 20px;'></button>
  <button class='border' style='width: 20px; height: 20px;'></button>
  <button class='border' style='width: 20px; height: 20px;'></button>
  <button class='border' style='width: 20px; height: 20px;'></button>
  <button class='border' style='width: 20px; height: 20px;'></button>
  <button class='border' style='width: 20px; height: 20px;'></button>
  <button class='border' style='width: 20px; height: 20px;'></button>
  <button class='border' style='width: 20px; height: 20px;'></button>
  <button class='border' style='width: 20px; height: 20px;'></button>
  <button class='border' style='width: 20px; height: 20px;'></button>
  <button class='border' style='width: 20px; height: 20px;'></button>
  <button class='border' style='width: 20px; height: 20px;'></button>
  <button class='border' style='width: 20px; height: 20px;'></button>
  <button class='border' style='width: 20px; height: 20px;'></button>
  <button class='border' style='width: 20px; height: 20px;'></button>
  <button class='border' style='width: 20px; height: 20px;'></button>
  <button class='border' style='width: 20px; height: 20px;'></button>
  <button class='border' style='width: 20px; height: 20px;'></button>
  <button class='border' style='width: 20px; height: 20px;'></button>
  <button class='border' style='width: 20px; height: 20px;'></button>
  <button class='border' style='width: 20px; height: 20px;'></button>
  <button class='border' style='width: 20px; height: 20px;'></button>
  <button class='border' style='width: 20px; height: 20px;'></button>
  <button class='border' style='width: 20px; height: 20px;'></button>
  <button class='border' style='width: 20px; height: 20px;'></button>
  <button class='border' style='width: 20px; height: 20px;'></button>
  <button class='border' style='width: 20px; height: 20px;'></button>
  <button class='border' style='width: 20px; height: 20px;'></button>
  <button class='border' style='width: 20px; height: 20px;'></button>
  <button class='border' style='width: 20px; height: 20px;'></button>
  <button class='border' style='width: 20px; height: 20px;'></button>
  <button class='border' style='width: 20px; height: 20px;'></button>
  <button class='border' style='width: 20px; height: 20px;'></button>
  <button class='border' style='width: 20px; height: 20px;'></button>
  <button class='border' style='width: 20px; height: 20px;'></button>
  <button class='border' style='width: 20px; height: 20px;'></button>
  <button class='border' style='width: 20px; height: 20px;'></button>
  <button class='border' style='width: 20px; height: 20px;'></button>
  <button class='border' style='width: 20px; height: 20px;'></button>
  <button class='border' style='width: 20px; height: 20px;'></button>
  <button class='border' style='width: 20px; height: 20px;'></button>
  <button class='border' style='width: 20px; height: 20px;'></button>
  <button class='border' style='width: 20px; height: 20px;'></button>
  <button class='border' style='width: 20px; height: 20px;'></button>
  <button class='border' style='width: 20px; height: 20px;'></button>
  <button class='border' style='width: 20px; height: 20px;'></button>
  <button class='border' style='width: 20px; height: 20px;'></button>
  <button class='border' style='width: 20px; height: 20px;'></button>
  <button class='border' style='width: 20px; height: 20px;'></button>
  <button class='border' style='width: 20px; height: 20px;'></button>
  <button class='border' style='width: 20px; height: 20px;'></button>
  <button class='border' style='width: 20px; height: 20px;'></button>
  <button class='border' style='width: 20px; height: 20px;'></button>
  <button class='border' style='width: 20px; height: 20px;'></button>
  <button class='border' style='width: 20px; height: 20px;'></button>
  <button class='border' style='width: 20px; height: 20px;'></button>
  <button class='border' style='width: 20px; height: 20px;'></button>
  <button class='border' style='width: 20px; height: 20px;'></button>
  <button class='border' style='width: 20px; height: 20px;'></button>
  <button class='border' style='width: 20px; height: 20px;'></button>
  <button class='border' style='width: 20px; height: 20px;'></button>
  <button class='border' style='width: 20px; height: 20px;'></button>
  <button class='border' style='width: 20px; height: 20px;'></button>
  <button class='border' style='width: 20px; height: 20px;'></button>
  <button class='border' style='width: 20px; height: 20px;'></button>
  <button class='border' style='width: 20px; height: 20px;'></button>
  <button class='border' style='width: 20px; height: 20px;'></button>
  <button class='border' style='width: 20px; height: 20px;'></button>
  <button class='border' style='width: 20px; height: 20px;'></button>
  <button class='border' style='width: 20px; height: 20px;'></button>
  <button class='border' style='width: 20px; height: 20px;'></button>
  <button class='border' style='width: 20px; height: 20px;'></button>
  <button class='border' style='width: 20px; height: 20px;'></button>
  <button class='border' style='width: 20px; height: 20px;'></button>
  <button class='border' style='width: 20px; height: 20px;'></button>
  <button class='border' style='width: 20px; height: 20px;'></button>
  <button class='border' style='width: 20px; height: 20px;'></button>
  <button class='border' style='width: 20px; height: 20px;'></button>
  <button class='border' style='width: 20px; height: 20px;'></button>
  <button class='border' style='width: 20px; height: 20px;'></button>
  <button class='border' style='width: 20px; height: 20px;'></button>
  <button class='border' style='width: 20px; height: 20px;'></button>
  <button class='border' style='width: 20px; height: 20px;'></button>
  <button class='border' style='width: 20px; height: 20px;'></button>
  <button class='border' style='width: 20px; height: 20px;'></button>
  <button class='border' style='width: 20px; height: 20px;'></button>
  <button class='border' style='width: 20px; height: 20px;'></button>
  <button class='border' style='width: 20px; height: 20px;'></button>
  <button class='border' style='width: 20px; height: 20px;'></button>
  <button class='border' style='width: 20px; height: 20px;'></button>
  <button class='border' style='width: 20px; height: 20px;'></button>
  <button class='border' style='width: 20px; height: 20px;'></button>
  <button class='border' style='width: 20px; height: 20px;'></button>
  <button class='border' style='width: 20px; height: 20px;'></button>
  <button class='border' style='width: 20px; height: 20px;'></button>
  <button class='border' style='width: 20px; height: 20px;'></button>
  <button class='border' style='width: 20px; height: 20px;'></button>
  <button class='border' style='width: 20px; height: 20px;'></button>
  <button class='border' style='width: 20px; height: 20px;'></button>
  <button class='border' style='width: 20px; height: 20px;'></button>
  <button class='border' style='width: 20px; height: 20px;'></button>
  <button class='border' style='width: 20px; height: 20px;'></button>
  <button class='border' style='width: 20px; height: 20px;'></button>
  <button class='border' style='width: 20px; height: 20px;'></button>
  <button class='border' style='width: 20px; height: 20px;'></button>
  <button class='border' style='width: 20px; height: 20px;'></button>
  <button class='border' style='width: 20px; height: 20px;'></button>
  <button class='border' style='width: 20px; height: 20px;'></button>
  <button class='border' style='width: 20px; height: 20px;'></button>
  <button class='border' style='width: 20px; height: 20px;'></button>
  <button class='border' style='width: 20px; height: 20px;'></button>
  <button class='border' style='width: 20px; height: 20px;'></button>
  <button class='border' style='width: 20px; height: 20px;'></button>
  <button class='border' style='width: 20px; height: 20px;'></button>
  <button class='border' style='width: 20px; height: 20px;'></button>
  <button class='border' style='width: 20px; height: 20px;'></button>
  <button class='border' style='width: 20px; height: 20px;'></button>
  <button class='border' style='width: 20px; height: 20px;'></button>
  <button class='border' style='width: 20px; height: 20px;'></button>
  <button class='border' style='width: 20px; height: 20px;'></button>
  <button class='border' style='width: 20px; height: 20px;'></button>
  <button class='border' style='width: 20px; height: 20px;'></button>
  <button class='border' style='width: 20px; height: 20px;'></button>
  <button class='border' style='width: 20px; height: 20px;'></button>
  <button class='border' style='width: 20px; height: 20px;'></button>
  <button class='border' style='width: 20px; height: 20px;'></button>
  <button class='border' style='width: 20px; height: 20px;'></button>
  <button class='border' style='width: 20px; height: 20px;'></button>
  <button class='border' style='width: 20px; height: 20px;'></button>
  <button class='border' style='width: 20px; height: 20px;'></button>
  <button class='border' style='width: 20px; height: 20px;'></button>
  <button class='border' style='width: 20px; height: 20px;'></button>
  <button class='border' style='width: 20px; height: 20px;'></button>
  <button class='border' style='width: 20px; height: 20px;'></button>
  <button class='border' style='width: 20px; height: 20px;'></button>
  <button class='border' style='width: 20px; height: 20px;'></button>
  <button class='border' style='width: 20px; height: 20px;'></button>
  <button class='border' style='width: 20px; height: 20px;'></button>
  <button class='border' style='width: 20px; height: 20px;'></button>
  <button class='border' style='width: 20px; height: 20px;'></button>
  <button class='border' style='width: 20px; height: 20px;'></button>
  <button class='border' style='width: 20px; height: 20px;'></button>
  <button class='border' style='width: 20px; height: 20px;'></button>
  <button class='border' style='width: 20px; height: 20px;'></button>
  <button class='border' style='width: 20px; height: 20px;'></button>
  <button class='border' style='width: 20px; height: 20px;'></button>
  <button class='border' style='width: 20px; height: 20px;'></button>
  <button class='border' style='width: 20px; height: 20px;'></button>
  <button class='border' style='width: 20px; height: 20px;'></button>
  <button class='border' style='width: 20px; height: 20px;'></button>
  <button class='border' style='width: 20px; height: 20px;'></button>
  <button class='border' style='width: 20px; height: 20px;'></button>
  <button class='border' style='width: 20px; height: 20px;'></button>
  <button class='border' style='width: 20px; height: 20px;'></button>
  <button class='border' style='width: 20px; height: 20px;'></button>
  <button class='border' style='width: 20px; height: 20px;'></button>
  <button class='border' style='width: 20px; height: 20px;'></button>
  <button class='border' style='width: 20px; height: 20px;'></button>
  <button class='border' style='width: 20px; height: 20px;'></button>
  <button class='border' style='width: 20px; height: 20px;'></button>
  <button class='border' style='width: 20px; height: 20px;'></button>
  <button class='border' style='width: 20px; height: 20px;'></button>
  <button class='border' style='width: 20px; height: 20px;'></button>
  <button class='border' style='width: 20px; height: 20px;'></button>
  <button class='border' style='width: 20px; height: 20px;'></button>
  <button class='border' style='width: 20px; height: 20px;'></button>
  <button class='border' style='width: 20px; height: 20px;'></button>
  <button class='border' style='width: 20px; height: 20px;'></button>
  <button class='border' style='width: 20px; height: 20px;'></button>
  <button class='border' style='width: 20px; height: 20px;'></button>
  <button class='border' style='width: 20px; height: 20px;'></button>
  <button class='border' style='width: 20px; height: 20px;'></button>
  <button class='border' style='width: 20px; height: 20px;'></button>
  <button class='border' style='width: 20px; height: 20px;'></button>
  <button class='border' style='width: 20px; height: 20px;'></button>
  <button class='border' style='width: 20px; height: 20px;'></button>
  <button class='border' style='width: 20px; height: 20px;'></button>
  <button class='border' style='width: 20px; height: 20px;'></button>
  <button class='border' style='width: 20px; height: 20px;'></button>
  <button class='border' style='width: 20px; height: 20px;'></button>
  <button class='border' style='width: 20px; height: 20px;'></button>
  <button class='border' style='width: 20px; height: 20px;'></button>
  <button class='border' style='width: 20px; height: 20px;'></button>
  <button class='border' style='width: 20px; height: 20px;'></button>
  <button class='border' style='width: 20px; height: 20px;'></button>
  <button class='border' style='width: 20px; height: 20px;'></button>
  <button class='border' style='width: 20px; height: 20px;'></button>
  <button class='border' style='width: 20px; height: 20px;'></button>
  <button class='border' style='width: 20px; height: 20px;'></button>
  <button class='border' style='width: 20px; height: 20px;'></button>
  <button class='border' style='width: 20px; height: 20px;'></button>
  <button class='border' style='width: 20px; height: 20px;'></button>
  <button class='border' style='width: 20px; height: 20px;'></button>
  <button class='border' style='width: 20px; height: 20px;'></button>
  <button class='border' style='width: 20px; height: 20px;'></button>
  <button class='border' style='width: 20px; height: 20px;'></button>
  <button class='border' style='width: 20px; height: 20px;'></button>
  <button class='border' style='width: 20px; height: 20px;'></button>
  <button class='border' style='width: 20px; height: 20px;'></button>
  <button class='border' style='width: 20px; height: 20px;'></button>
  <button class='border' style='width: 20px; height: 20px;'></button>
  <button class='border' style='width: 20px; height: 20px;'></button>
  <button class='border' style='width: 20px; height: 20px;'></button>
  <button class='border' style='width: 20px; height: 20px;'></button>
  <button class='border' style='width: 20px; height: 20px;'></button>
  <button class='border' style='width: 20px; height: 20px;'></button>
  <button class='border' style='width: 20px; height: 20px;'></button>
  <button class='border' style='width: 20px; height: 20px;'></button>
  <button class='border' style='width: 20px; height: 20px;'></button>
  <button class='border' style='width: 20px; height: 20px;'></button>
  <button class='border' style='width: 20px; height: 20px;'></button>
  <button class='border' style='width: 20px; height: 20px;'></button>
  <button class='border' style='width: 20px; height: 20px;'></button>
  <button class='border' style='width: 20px; height: 20px;'></button>
  <button class='border' style='width: 20px; height: 20px;'></button>
  <button class='border' style='width: 20px; height: 20px;'></button>
  <button class='border' style='width: 20px; height: 20px;'></button>
  <button class='border' style='width: 20px; height: 20px;'></button>
  <button class='border' style='width: 20px; height: 20px;'></button>
  <button class='border' style='width: 20px; height: 20px;'></button>
  <button class='border' style='width: 20px; height: 20px;'></button>
  <button class='border' style='width: 20px; height: 20px;'></button>
  <button class='border' style='width: 20px; height: 20px;'></button>
  <button class='border' style='width: 20px; height: 20px;'></button>
  <button class='border' style='width: 20px; height: 20px;'></button>
  <button class='border' style='width: 20px; height: 20px;'></button>
  <button class='border' style='width: 20px; height: 20px;'></button>
  <button class='border' style='width: 20px; height: 20px;'></button>
  <button class='border' style='width: 20px; height: 20px;'></button>
  <button class='border' style='width: 20px; height: 20px;'></button>
</div>;
